import { jsPDF } from 'jspdf';

interface PDFOptions {
  title: string;
  content: string;
  filename: string;
}

export function exportToPDF({ title, content, filename }: PDFOptions): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // ── Header bar ──────────────────────────────────────────────────────────────
  doc.setFillColor(13, 148, 136); // teal-600
  doc.rect(0, 0, pageWidth, 18, 'F');

  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('FreelanceKit', margin, 12);

  // Date on right
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  doc.text(dateStr, pageWidth - margin, 12, { align: 'right' });

  // ── Title ────────────────────────────────────────────────────────────────────
  doc.setTextColor(17, 24, 39); // gray-900
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 32);

  // Divider line
  doc.setDrawColor(209, 213, 219); // gray-300
  doc.setLineWidth(0.3);
  doc.line(margin, 36, pageWidth - margin, 36);

  // ── Body content ─────────────────────────────────────────────────────────────
  doc.setFontSize(9.5);
  doc.setFont('courier', 'normal');
  doc.setTextColor(55, 65, 81); // gray-700

  const lines = doc.splitTextToSize(content, contentWidth);
  let y = 44;
  const lineHeight = 5.5;

  for (const line of lines) {
    if (y + lineHeight > pageHeight - 16) {
      // Footer before new page
      addFooter(doc, pageWidth, pageHeight, margin);
      doc.addPage();

      // Page header
      doc.setFillColor(13, 148, 136);
      doc.rect(0, 0, pageWidth, 10, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text('FreelanceKit — ' + title, margin, 7);

      y = 18;
      doc.setFontSize(9.5);
      doc.setFont('courier', 'normal');
      doc.setTextColor(55, 65, 81);
    }

    // Highlight section headers (lines with ═ or ─)
    if (line.includes('═') || line.includes('─')) {
      doc.setTextColor(13, 148, 136);
      doc.setFont('courier', 'bold');
    } else if (line.toUpperCase() === line && line.trim().length > 3 && !line.includes(' ') === false && line.trim().length < 40) {
      doc.setTextColor(17, 24, 39);
      doc.setFont('courier', 'bold');
    } else {
      doc.setTextColor(55, 65, 81);
      doc.setFont('courier', 'normal');
    }

    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer on last page
  addFooter(doc, pageWidth, pageHeight, margin);

  // Save
  doc.save(filename.replace('.txt', '.pdf'));
}

function addFooter(doc: jsPDF, pageWidth: number, pageHeight: number, margin: number): void {
  doc.setFillColor(249, 250, 251); // gray-50
  doc.rect(0, pageHeight - 12, pageWidth, 12, 'F');
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.2);
  doc.line(0, pageHeight - 12, pageWidth, pageHeight - 12);

  doc.setTextColor(156, 163, 175); // gray-400
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by FreelanceKit — freelancekit-zeta.vercel.app', margin, pageHeight - 5);
  doc.text(
    `Page ${doc.getNumberOfPages()}`,
    pageWidth - margin,
    pageHeight - 5,
    { align: 'right' }
  );
}
