import { jsPDF } from 'jspdf';

interface PDFOptions {
  title: string;
  content: string;
  filename: string;
}

export function exportToPDF({ title, content, filename }: PDFOptions): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const ml = 25, mr = 25;
  const cw = pw - ml - mr;
  let currentPage = 1;

  // Clean non-latin1 characters
  const clean = content
    .replace(/[═─]+/g, '---DIV---')
    .replace(/[✓]/g, '[YES]')
    .replace(/[✗]/g, '[NO]')
    .replace(/[•]/g, '-')
    .replace(/[^\x00-\xFF]/g, '');

  function drawPage() {
    // Page background
    doc.setFillColor(252, 252, 253);
    doc.rect(0, 0, pw, ph, 'F');

    // ── Left sidebar ──────────────────────────────────────────────────────────
    doc.setFillColor(13, 148, 136);
    doc.rect(0, 0, 8, ph, 'F');

    // Sidebar accent dots
    doc.setFillColor(255, 255, 255, 0.3);
    for (let i = 0; i < 5; i++) {
      doc.setFillColor(255, 255, 255);
      doc.circle(4, ph - 20 - i * 8, 0.8, 'F');
    }

    // ── Top header ────────────────────────────────────────────────────────────
    doc.setFillColor(17, 24, 39);
    doc.rect(8, 0, pw - 8, 28, 'F');

    // Brand name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('FreelanceKit', 16, 14);

    // Brand subtitle
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(156, 163, 175);
    doc.text('AI-POWERED FREELANCE TOOLKIT', 16, 21);

    // Date badge
    const dateStr = new Date().toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
    });
    doc.setFillColor(13, 148, 136);
    doc.roundedRect(pw - mr - 45, 8, 45, 12, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.text(dateStr, pw - mr - 22.5, 15.5, { align: 'center' });

    // Page number (if not first)
    if (currentPage > 1) {
      doc.setFillColor(13, 148, 136);
      doc.roundedRect(pw - mr - 20, 8, 20, 12, 2, 2, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text(`${currentPage}`, pw - mr - 10, 15.5, { align: 'center' });
    }

    // ── Footer ────────────────────────────────────────────────────────────────
    doc.setFillColor(17, 24, 39);
    doc.rect(8, ph - 16, pw - 8, 16, 'F');

    doc.setTextColor(75, 85, 99);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(156, 163, 175);
    doc.text('Generated by FreelanceKit', 16, ph - 9);
    doc.text('freelancekit-zeta.vercel.app', 16, ph - 4.5);

    // Footer right - teal accent line
    doc.setFillColor(13, 148, 136);
    doc.rect(pw - 40, ph - 16, 40, 16, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('CONFIDENTIAL', pw - 20, ph - 7, { align: 'center' });
  }

  // ── Page 1 title section ───────────────────────────────────────────────────
  drawPage();

  // Title area with big teal box
  doc.setFillColor(240, 253, 250);
  doc.roundedRect(ml, 33, cw, 22, 3, 3, 'F');
  doc.setDrawColor(13, 148, 136);
  doc.setLineWidth(0.8);
  doc.line(ml, 33, ml, 55); // left border accent

  doc.setTextColor(13, 148, 136);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('DOCUMENT', ml + 4, 40);

  doc.setTextColor(17, 24, 39);
  doc.setFontSize(17);
  doc.setFont('helvetica', 'bold');
  // Truncate title if too long
  const shortTitle = title.length > 55 ? title.substring(0, 55) + '...' : title;
  doc.text(shortTitle, ml + 4, 51);

  // Subtle grid pattern area
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.1);
  for (let x = ml; x < pw - mr; x += 5) {
    doc.line(x, 60, x, 65);
  }

  let y = 68;
  const lh = 5.8;
  const bottom = ph - 20;

  const lines = clean.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const t = line.trim();

    if (y > bottom) {
      currentPage++;
      doc.addPage();
      drawPage();
      y = 35;
    }

    // Empty
    if (t === '') { y += 2; continue; }

    // Divider
    if (t === '---DIV---') {
      // Draw a styled divider with dots
      doc.setDrawColor(209, 213, 219);
      doc.setLineWidth(0.2);
      doc.line(ml, y, pw - mr, y);
      doc.setFillColor(13, 148, 136);
      doc.circle(ml + cw / 2, y, 0.8, 'F');
      doc.circle(ml + cw / 2 - 6, y, 0.5, 'F');
      doc.circle(ml + cw / 2 + 6, y, 0.5, 'F');
      y += 5;
      continue;
    }

    // Section heading
    const isHeading = t === t.toUpperCase()
      && t.length > 3 && t.length < 55
      && /[A-Z]/.test(t)
      && !t.includes(':')
      && !t.startsWith('-')
      && !t.startsWith('[');

    if (isHeading) {
      y += 2;
      if (y > bottom - 12) {
        currentPage++;
        doc.addPage();
        drawPage();
        y = 35;
      }
      // Heading background
      doc.setFillColor(17, 24, 39);
      doc.roundedRect(ml, y - 4, cw, 9, 1.5, 1.5, 'F');
      // Teal left pip
      doc.setFillColor(13, 148, 136);
      doc.roundedRect(ml, y - 4, 3, 9, 1, 1, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      doc.text(t, ml + 6, y + 2);
      y += 12;
      continue;
    }

    // Key: value lines
    if (t.includes(':') && t.indexOf(':') < 25 && !t.startsWith('-')) {
      const colonIdx = t.indexOf(':');
      const key = t.substring(0, colonIdx + 1);
      const val = t.substring(colonIdx + 1).trim();

      doc.setTextColor(13, 148, 136);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      doc.text(key, ml + 2, y);

      if (val) {
        doc.setTextColor(55, 65, 81);
        doc.setFont('helvetica', 'normal');
        const valLines = doc.splitTextToSize(val, cw - 45);
        doc.text(valLines[0], ml + 48, y);
        if (valLines.length > 1) {
          for (let vi = 1; vi < valLines.length; vi++) {
            y += lh;
            if (y > bottom) { currentPage++; doc.addPage(); drawPage(); y = 35; }
            doc.text(valLines[vi], ml + 48, y);
          }
        }
      }
      y += lh;
      continue;
    }

    // Bullet / list item
    if (t.startsWith('-') || t.startsWith('*')) {
      doc.setFillColor(13, 148, 136);
      doc.circle(ml + 3, y - 1.2, 1, 'F');
      doc.setTextColor(55, 65, 81);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const wrapped = doc.splitTextToSize(t.replace(/^[-*]\s*/, ''), cw - 8);
      for (const wl of wrapped) {
        if (y > bottom) { currentPage++; doc.addPage(); drawPage(); y = 35; }
        doc.text(wl, ml + 7, y);
        y += lh;
      }
      continue;
    }

    // Normal text
    doc.setTextColor(55, 65, 81);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const wrapped = doc.splitTextToSize(t, cw);
    for (const wl of wrapped) {
      if (y > bottom) { currentPage++; doc.addPage(); drawPage(); y = 35; }
      doc.text(wl, ml, y);
      y += lh;
    }
  }

  doc.save(filename.replace(/\.(txt|pdf)$/, '') + '.pdf');
}
